%%
%PhanOomega: reconstructing the carbonate chemistry of Phanerozoic seawater
%using ooid size data

%This code will regenerate the figures in the main text.

%This code was written by Lizzy Trower in Matlab R2021b. This version was
%last edited in October 2022.

%%
clear

%load relevant model run .mat file
load("MCv2data_01242022.mat")
load('AKdata_formation.mat','paleolat')

%%
%Data curation step to take out datapoints for which
%the mean particular Stokes number is below the threshold, since those
%grains do not have sufficient kinetic energy relative to fluid viscosity
%to abrade and therefore the equilibrium ooid size model cannot be applied.

%This uses the 95th percentile Stokes # - still includes grains for which
%>5% of simulations are large enough to abrade (so pretty conservative in
%excluding data).

Stokes_95 = prctile(real(Stokes),95,2);
Stokes_thresh = find(Stokes_95>=9);

Omega_ca = Omega_ca(Stokes_thresh,:);
ages = ages(Stokes_thresh);
mineral = mineral(Stokes_thresh);
DIC = DIC(Stokes_thresh,:);
Alk = Alk(Stokes_thresh,:);
pH = pH(Stokes_thresh,:);
depenv = depenv(Stokes_thresh);
paleolat = paleolat(Stokes_thresh);

%%
%This will generate a panel of figures as shown in Figure 2 of the main
%text.

Figure2 = figure;

colors_lines = viridis(7);
colors = magma(4);
colors_pts = magma(5);

t_data1 = tiledlayout(4,2);

t_data1_ax1 = nexttile;

RidgwellOmega = readmatrix('Ridgwell_Omega.xlsx','Range','A2:B131');
ArvidsonOmega = readmatrix('Arvidson_Omega.xlsx','Range','A2:B47');
Arvidson2013Omega = readmatrix('Arvidson2013_Omega.xlsx','Range','A2:B80');
RidingLiangOmega = readmatrix('Riding_Liang_Omega.xlsx','Range','A2:B52');
AloisiOmega = readmatrix('Aloisi_Omega_update.xlsx','Range','A2:B152');
AloisiOmega_cats = categorical(readcell('Aloisi_Omega_update.xlsx',...
    'Range','C2:C152'));
AloisiOmega_mins = AloisiOmega(AloisiOmega_cats == 'min',:);
AloisiOmega_maxs = AloisiOmega(AloisiOmega_cats == 'max',:);

plot(RidgwellOmega(:,1),RidgwellOmega(:,2),'Color',colors_lines(1,:))
hold on
plot(ArvidsonOmega(:,1),ArvidsonOmega(:,2),'Color',colors_lines(2,:))
plot(RidingLiangOmega(:,1),RidingLiangOmega(:,2),'Color',colors_lines(4,:))
plot(Arvidson2013Omega(:,1),Arvidson2013Omega(:,2),'Color',colors_lines(3,:))
plot(AloisiOmega_mins(:,1),AloisiOmega_mins(:,2),'Color',colors_lines(7,:))
plot(AloisiOmega_maxs(:,1),AloisiOmega_maxs(:,2),'r')
xlim([0 550])
set(gca, 'xdir', 'reverse')
box on
ylabel('\Omega_C_a')
ylim([0 30])

t_data1_ax2 = nexttile;

Omega_ca_50 = prctile(Omega_ca',50);
Omega_ca_10 = prctile(Omega_ca',10);
Omega_ca_90 = prctile(Omega_ca',90);
neg = Omega_ca_50 - Omega_ca_10;
pos = Omega_ca_90 - Omega_ca_50;

Omega_ca_50 = Omega_ca_50';
neg = neg';
pos = pos';

errorbar(ages(mineral == 'aragonite' & depenv == 'shoal'),...
    Omega_ca_50(mineral == 'aragonite' & depenv == 'shoal'),...
   neg(mineral == 'aragonite' & depenv == 'shoal'),...
   pos(mineral == 'aragonite' & depenv == 'shoal'),'o',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
hold on
errorbar(ages(mineral == 'aragonite' & depenv == 'tidal'),...
    Omega_ca_50(mineral == 'aragonite' & depenv == 'tidal'),...
   neg(mineral == 'aragonite' & depenv == 'tidal'),...
   pos(mineral == 'aragonite' & depenv == 'tidal'),'d',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'high_energy'),...
    Omega_ca_50(mineral == 'aragonite' & depenv == 'high_energy'),...
   neg(mineral == 'aragonite' & depenv == 'high_energy'),...
   pos(mineral == 'aragonite' & depenv == 'high_energy'),'s',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'low_energy'),...
    Omega_ca_50(mineral == 'aragonite' & depenv == 'low_energy'),...
   neg(mineral == 'aragonite' & depenv == 'low_energy'),...
   pos(mineral == 'aragonite' & depenv == 'low_energy'),'v',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'other'),...
    Omega_ca_50(mineral == 'aragonite' & depenv == 'other'),...
   neg(mineral == 'aragonite' & depenv == 'other'),...
   pos(mineral == 'aragonite' & depenv == 'other'),'p',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'calcite' & depenv == 'shoal'),...
    Omega_ca_50(mineral == 'calcite' & depenv == 'shoal'),...
   neg(mineral == 'calcite' & depenv == 'shoal'),...
   pos(mineral == 'calcite' & depenv == 'shoal'),'o',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'tidal'),...
    Omega_ca_50(mineral == 'calcite' & depenv == 'tidal'),...
   neg(mineral == 'calcite' & depenv == 'tidal'),...
   pos(mineral == 'calcite' & depenv == 'tidal'),'d',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'high_energy'),...
    Omega_ca_50(mineral == 'calcite' & depenv == 'high_energy'),...
   neg(mineral == 'calcite' & depenv == 'high_energy'),...
   pos(mineral == 'calcite' & depenv == 'high_energy'),'s',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'low_energy'),...
    Omega_ca_50(mineral == 'calcite' & depenv == 'low_energy'),...
   neg(mineral == 'calcite' & depenv == 'low_energy'),...
   pos(mineral == 'calcite' & depenv == 'low_energy'),'v',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'other'),...
    Omega_ca_50(mineral == 'calcite' & depenv == 'other'),...
   neg(mineral == 'calcite' & depenv == 'other'),...
   pos(mineral == 'calcite' & depenv == 'other'),'p',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'shoal'),...
    Omega_ca_50(mineral == 'bimineralic' & depenv == 'shoal'),...
   neg(mineral == 'bimineralic' & depenv == 'shoal'),...
   pos(mineral == 'bimineralic' & depenv == 'shoal'),'o',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'tidal'),...
    Omega_ca_50(mineral == 'bimineralic' & depenv == 'tidal'),...
   neg(mineral == 'bimineralic' & depenv == 'tidal'),...
   pos(mineral == 'bimineralic' & depenv == 'tidal'),'d',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'high_energy'),...
    Omega_ca_50(mineral == 'bimineralic' & depenv == 'high_energy'),...
   neg(mineral == 'bimineralic' & depenv == 'high_energy'),...
   pos(mineral == 'bimineralic' & depenv == 'high_energy'),'s',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'low_energy'),...
    Omega_ca_50(mineral == 'bimineralic' & depenv == 'low_energy'),...
   neg(mineral == 'bimineralic' & depenv == 'low_energy'),...
   pos(mineral == 'bimineralic' & depenv == 'low_energy'),'v',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'other'),...
    Omega_ca_50(mineral == 'bimineralic' & depenv == 'other'),...
   neg(mineral == 'bimineralic' & depenv == 'other'),...
   pos(mineral == 'bimineralic' & depenv == 'other'),'p',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))

[agesort,sortorder] = sort(ages);
Omega_ca_50_sort = Omega_ca_50(sortorder);
loessfit = smooth(agesort,Omega_ca_50_sort,0.1,'rlowess');

f = @(xy) smooth(xy(:,1),xy(:,2),0.1,'rlowess');
yboot2 = bootstrp(1000,f,[agesort,Omega_ca_50_sort]);
stdloess = std(yboot2);

plot(agesort,loessfit,'k')
plot(agesort,loessfit+stdloess','r')
plot(agesort,loessfit-stdloess','r')

xlim([0 550])
set(gca, 'xdir', 'reverse')
box on
ylim([0 30])

t_data1_ax3 = nexttile;

RidgwellpH = readmatrix('Ridgwell_pH.xlsx','Range','A2:B103');
ArvidsonpH = readmatrix('Arvidson_pH.xlsx','Range','A2:B108');
Arvidson2013pH = readmatrix('Arvidson2013_pH.xlsx','Range','A2:B85');
RidingLiangpH = readmatrix('Riding_Liang_pH.xlsx','Range','A2:B77');
ZT19Alkn = readmatrix("ZT19.Alkn.xlsx",'Range','A2:F255');
ZT19GCRB = readmatrix("ZT19.GCRB.xlsx",'Sheet','ZT19 GCRB','Range',...
    'B2:G13');
AloisipH = readmatrix('Aloisi_pH_update.xlsx','Range','A2:B165');
AloisipH_cats = categorical(readcell('Aloisi_pH_update.xlsx',...
    'Range','C2:C165'));
AloisipH_mins = AloisipH(AloisipH_cats == 'min',:);
AloisipH_maxs = AloisipH(AloisipH_cats == 'max',:);

Anagnostou_pH = readmatrix('Anagnostou_pHproxydata.xlsx','Sheet',...
    'Table 1','Range','I6:I95');
Anagnostou_pH(isnan(Anagnostou_pH)) = [];
Anagnostou_age = zeros(length(Anagnostou_pH),1);
Anagnostou_age(1:11) = 53.2;
Anagnostou_age(12:23) = 45.6;
Anagnostou_age(24:30) = 44.4;
Anagnostou_age(31:48) = 40.3;
Anagnostou_age(49:51) = 36.9;
Anagnostou_age(52:end) = 0.01;

Sosdian_pH_pp_age = readmatrix('Sosdian_pH_pp.xlsx','Sheet',...
    'Plio-Pleistocene','Range','C3:C327');
Sosdian_pH_pp = readmatrix('Sosdian_pH_pp.xlsx','Sheet',...
    'Plio-Pleistocene','Range','G3:G327');
Sosdian_pH_pp(isnan(Sosdian_pH_pp)) = [];
Sosdian_pH_pp(Sosdian_pH_pp == 0.5) = [];
Sosdian_pH_pp_age(isnan(Sosdian_pH_pp_age)) = [];

Sosdian_pH_ng_age = readmatrix('Sosdian_pH_ng.xlsx','Sheet',...
    'Planktic-HO-PA-RH','Range','C3:C412');
Sosdian_pH_ng = readmatrix('Sosdian_pH_ng.xlsx','Sheet',...
    'Planktic-HO-PA-RH','Range','G3:G412');
Sosdian_pH_ng_age(isnan(Sosdian_pH_ng_age)) = [];
Sosdian_pH_ng(isnan(Sosdian_pH_ng)) = [];
Sosdian_pH_ng(Sosdian_pH_ng == 0.5) = [];

Pearson_pH_age = readmatrix('Pearson_pH.xlsx','Sheet','Table 1',...
    'Range','C2:C13');
Pearson_pH = readmatrix('Pearson_pH.xlsx','Sheet','Table 1',...
    'Range','O2:O13');

Foster_pH_age = readmatrix('Foster_pH.xlsx','Range','F5:F27');
Foster_pH_age(isnan(Foster_pH_age)) = [];
Foster_pH = readmatrix('Foster_pH.xlsx','Range','U5:U27');
Foster_pH(isnan(Foster_pH)) = [];

plot(RidgwellpH(:,1),RidgwellpH(:,2),'Color',colors_lines(1,:));
hold on
plot(ArvidsonpH(:,1),ArvidsonpH(:,2),'Color',colors_lines(2,:));
plot(RidingLiangpH(:,1),RidingLiangpH(:,2),'Color',colors_lines(4,:));
plot(ZT19Alkn(:,1),ZT19Alkn(:,6),'Color',colors_lines(5,:))
plot(ZT19GCRB(:,1),ZT19GCRB(:,6),'Color',colors_lines(6,:))
plot(Arvidson2013pH(:,1),Arvidson2013pH(:,2),'Color',colors_lines(3,:));
plot(AloisipH_mins(:,1),AloisipH_mins(:,2),'Color',colors_lines(7,:))
plot(AloisipH_maxs(:,1),AloisipH_maxs(:,2),'r')
scatter(Anagnostou_age,Anagnostou_pH,[],colors_pts(1,:),'.')
%scatter(Sosdian_pH_pp_age,Sosdian_pH_pp,[],colors_pts(2,:),'.')
scatter(Sosdian_pH_ng_age,Sosdian_pH_ng,[],colors_pts(2,:),'.')
scatter(Pearson_pH_age,Pearson_pH,[],colors_pts(3,:),'.')
scatter(Foster_pH_age,Foster_pH,[],colors_pts(4,:),'.')

xlim([0 550])
set(gca, 'xdir', 'reverse')
box on
ylabel('pH')
ylim([7.2 8.4])


t_data1_ax4 = nexttile;

pH_50 = prctile(pH',50);
pH_10 = prctile(pH',10);
pH_90 = prctile(pH',90);
neg_pH = pH_50 - pH_10;
pos_pH = pH_90 - pH_50;

pH_50 = pH_50';
neg_pH = neg_pH';
pos_pH = pos_pH';

errorbar(ages(mineral == 'aragonite' & depenv == 'shoal'),...
    pH_50(mineral == 'aragonite' & depenv == 'shoal'),...
   neg_pH(mineral == 'aragonite' & depenv == 'shoal'),...
   pos_pH(mineral == 'aragonite' & depenv == 'shoal'),'o',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
hold on
errorbar(ages(mineral == 'aragonite' & depenv == 'tidal'),...
    pH_50(mineral == 'aragonite' & depenv == 'tidal'),...
   neg_pH(mineral == 'aragonite' & depenv == 'tidal'),...
   pos_pH(mineral == 'aragonite' & depenv == 'tidal'),'d',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'high_energy'),...
    pH_50(mineral == 'aragonite' & depenv == 'high_energy'),...
   neg_pH(mineral == 'aragonite' & depenv == 'high_energy'),...
   pos_pH(mineral == 'aragonite' & depenv == 'high_energy'),'s',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'low_energy'),...
    pH_50(mineral == 'aragonite' & depenv == 'low_energy'),...
   neg_pH(mineral == 'aragonite' & depenv == 'low_energy'),...
   pos_pH(mineral == 'aragonite' & depenv == 'low_energy'),'v',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'other'),...
    pH_50(mineral == 'aragonite' & depenv == 'other'),...
   neg_pH(mineral == 'aragonite' & depenv == 'other'),...
   pos_pH(mineral == 'aragonite' & depenv == 'other'),'p',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'calcite' & depenv == 'shoal'),...
    pH_50(mineral == 'calcite' & depenv == 'shoal'),...
   neg_pH(mineral == 'calcite' & depenv == 'shoal'),...
   pos_pH(mineral == 'calcite' & depenv == 'shoal'),'o',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'tidal'),...
    pH_50(mineral == 'calcite' & depenv == 'tidal'),...
   neg_pH(mineral == 'calcite' & depenv == 'tidal'),...
   pos_pH(mineral == 'calcite' & depenv == 'tidal'),'d',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'high_energy'),...
    pH_50(mineral == 'calcite' & depenv == 'high_energy'),...
   neg_pH(mineral == 'calcite' & depenv == 'high_energy'),...
   pos_pH(mineral == 'calcite' & depenv == 'high_energy'),'s',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'low_energy'),...
    pH_50(mineral == 'calcite' & depenv == 'low_energy'),...
   neg_pH(mineral == 'calcite' & depenv == 'low_energy'),...
   pos_pH(mineral == 'calcite' & depenv == 'low_energy'),'v',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'other'),...
    pH_50(mineral == 'calcite' & depenv == 'other'),...
   neg_pH(mineral == 'calcite' & depenv == 'other'),...
   pos_pH(mineral == 'calcite' & depenv == 'other'),'p',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'shoal'),...
    pH_50(mineral == 'bimineralic' & depenv == 'shoal'),...
   neg_pH(mineral == 'bimineralic' & depenv == 'shoal'),...
   pos_pH(mineral == 'bimineralic' & depenv == 'shoal'),'o',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'tidal'),...
    pH_50(mineral == 'bimineralic' & depenv == 'tidal'),...
   neg_pH(mineral == 'bimineralic' & depenv == 'tidal'),...
   pos_pH(mineral == 'bimineralic' & depenv == 'tidal'),'d',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'high_energy'),...
    pH_50(mineral == 'bimineralic' & depenv == 'high_energy'),...
   neg_pH(mineral == 'bimineralic' & depenv == 'high_energy'),...
   pos_pH(mineral == 'bimineralic' & depenv == 'high_energy'),'s',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'low_energy'),...
    pH_50(mineral == 'bimineralic' & depenv == 'low_energy'),...
   neg_pH(mineral == 'bimineralic' & depenv == 'low_energy'),...
   pos_pH(mineral == 'bimineralic' & depenv == 'low_energy'),'v',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'other'),...
    pH_50(mineral == 'bimineralic' & depenv == 'other'),...
   neg_pH(mineral == 'bimineralic' & depenv == 'other'),...
   pos_pH(mineral == 'bimineralic' & depenv == 'other'),'p',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))

pH_50_sort = pH_50(sortorder);
loessfit_pH = smooth(agesort,pH_50_sort,0.1,'rlowess');

%f = @(xy) smooth(xy(:,1),xy(:,2),0.1,'rlowess');
yboot2_pH = bootstrp(1000,f,[agesort,pH_50_sort]);
stdloess_pH = std(yboot2_pH);

plot(agesort,loessfit_pH,'k')
plot(agesort,loessfit_pH+stdloess_pH','r')
plot(agesort,loessfit_pH-stdloess_pH','r')

xlim([0 550])
set(gca, 'xdir', 'reverse')
box on
ylim([7.2 8.4])

t_data1_ax5 = nexttile;

RidgwellDIC = readmatrix('Ridgwell.xlsx','Range','A2:B86');
ArvidsonDIC = readmatrix('Arvidson_DIC.xlsx','Range','A2:C105');
Arvidson2013DIC = readmatrix('Arvidson2013_DIC.xlsx','Range','A2:B84');

plot(RidgwellDIC(:,1),RidgwellDIC(:,2),'Color',colors_lines(1,:));
hold on
plot(ArvidsonDIC(:,1),ArvidsonDIC(:,3),'Color',colors_lines(2,:))
plot(ZT19Alkn(:,1),ZT19Alkn(:,4),'Color',colors_lines(5,:))
plot(ZT19GCRB(:,1),ZT19GCRB(:,4),'Color',colors_lines(6,:))
plot(Arvidson2013DIC(:,1),Arvidson2013DIC(:,2),'Color',colors_lines(3,:))
xlim([0 550])
set(gca, 'xdir', 'reverse')
box on
ylabel('DIC (mM)')
ylim([0 10])

t_data1_ax6 = nexttile;

DIC_50 = prctile(DIC',50);
DIC_10 = prctile(DIC',10);
DIC_90 = prctile(DIC',90);
neg_DIC = DIC_50 - DIC_10;
pos_DIC = DIC_90 - DIC_50;

DIC_50 = DIC_50';
neg_DIC = neg_DIC';
pos_DIC = pos_DIC';

errorbar(ages(mineral == 'aragonite' & depenv == 'shoal'),...
    DIC_50(mineral == 'aragonite' & depenv == 'shoal'),...
   neg_DIC(mineral == 'aragonite' & depenv == 'shoal'),...
   pos_DIC(mineral == 'aragonite' & depenv == 'shoal'),'o',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
hold on
errorbar(ages(mineral == 'aragonite' & depenv == 'tidal'),...
    DIC_50(mineral == 'aragonite' & depenv == 'tidal'),...
   neg_DIC(mineral == 'aragonite' & depenv == 'tidal'),...
   pos_DIC(mineral == 'aragonite' & depenv == 'tidal'),'d',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'high_energy'),...
    DIC_50(mineral == 'aragonite' & depenv == 'high_energy'),...
   neg_DIC(mineral == 'aragonite' & depenv == 'high_energy'),...
   pos_DIC(mineral == 'aragonite' & depenv == 'high_energy'),'s',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'low_energy'),...
    DIC_50(mineral == 'aragonite' & depenv == 'low_energy'),...
   neg_DIC(mineral == 'aragonite' & depenv == 'low_energy'),...
   pos_DIC(mineral == 'aragonite' & depenv == 'low_energy'),'v',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'other'),...
    DIC_50(mineral == 'aragonite' & depenv == 'other'),...
   neg_DIC(mineral == 'aragonite' & depenv == 'other'),...
   pos_DIC(mineral == 'aragonite' & depenv == 'other'),'p',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'calcite' & depenv == 'shoal'),...
    DIC_50(mineral == 'calcite' & depenv == 'shoal'),...
   neg_DIC(mineral == 'calcite' & depenv == 'shoal'),...
   pos_DIC(mineral == 'calcite' & depenv == 'shoal'),'o',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'tidal'),...
    DIC_50(mineral == 'calcite' & depenv == 'tidal'),...
   neg_DIC(mineral == 'calcite' & depenv == 'tidal'),...
   pos_DIC(mineral == 'calcite' & depenv == 'tidal'),'d',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'high_energy'),...
    DIC_50(mineral == 'calcite' & depenv == 'high_energy'),...
   neg_DIC(mineral == 'calcite' & depenv == 'high_energy'),...
   pos_DIC(mineral == 'calcite' & depenv == 'high_energy'),'s',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'low_energy'),...
    DIC_50(mineral == 'calcite' & depenv == 'low_energy'),...
   neg_DIC(mineral == 'calcite' & depenv == 'low_energy'),...
   pos_DIC(mineral == 'calcite' & depenv == 'low_energy'),'v',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'other'),...
    DIC_50(mineral == 'calcite' & depenv == 'other'),...
   neg_DIC(mineral == 'calcite' & depenv == 'other'),...
   pos_DIC(mineral == 'calcite' & depenv == 'other'),'p',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'shoal'),...
    DIC_50(mineral == 'bimineralic' & depenv == 'shoal'),...
   neg_DIC(mineral == 'bimineralic' & depenv == 'shoal'),...
   pos_DIC(mineral == 'bimineralic' & depenv == 'shoal'),'o',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'tidal'),...
    DIC_50(mineral == 'bimineralic' & depenv == 'tidal'),...
   neg_DIC(mineral == 'bimineralic' & depenv == 'tidal'),...
   pos_DIC(mineral == 'bimineralic' & depenv == 'tidal'),'d',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'high_energy'),...
    DIC_50(mineral == 'bimineralic' & depenv == 'high_energy'),...
   neg_DIC(mineral == 'bimineralic' & depenv == 'high_energy'),...
   pos_DIC(mineral == 'bimineralic' & depenv == 'high_energy'),'s',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'low_energy'),...
    DIC_50(mineral == 'bimineralic' & depenv == 'low_energy'),...
   neg_DIC(mineral == 'bimineralic' & depenv == 'low_energy'),...
   pos_DIC(mineral == 'bimineralic' & depenv == 'low_energy'),'v',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'other'),...
    DIC_50(mineral == 'bimineralic' & depenv == 'other'),...
   neg_DIC(mineral == 'bimineralic' & depenv == 'other'),...
   pos_DIC(mineral == 'bimineralic' & depenv == 'other'),'p',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))

DIC_50_sort = DIC_50(sortorder);
loessfit_DIC = smooth(agesort,DIC_50_sort,0.1,'rlowess');

%f = @(xy) smooth(xy(:,1),xy(:,2),0.1,'rlowess');
yboot2_DIC = bootstrp(1000,f,[agesort,DIC_50_sort]);
stdloess_DIC = std(yboot2_DIC);

plot(agesort,loessfit_DIC,'k')
plot(agesort,loessfit_DIC+stdloess_DIC','r')
plot(agesort,loessfit_DIC-stdloess_DIC','r')

xlim([0 550])
set(gca, 'xdir', 'reverse')
box on
ylim([0 10])

t_data1_ax7 = nexttile;

AloisiAlk = readmatrix('Aloisi_Alk_update.xlsx','Range','A2:B241');
AloisiAlk_cats = categorical(readcell('Aloisi_Alk_update.xlsx',...
    'Range','C2:C241'));
AloisiAlk_mins = AloisiAlk(AloisiAlk_cats == 'min',:);
AloisiAlk_maxs = AloisiAlk(AloisiAlk_cats == 'max',:);


plot(ZT19Alkn(:,1),ZT19Alkn(:,5),'Color',colors_lines(5,:))
hold on
plot(ZT19GCRB(:,1),ZT19GCRB(:,5),'Color',colors_lines(6,:))
plot(AloisiAlk_mins(:,1),AloisiAlk_mins(:,2),'Color',colors_lines(7,:))
plot(AloisiAlk_maxs(:,1),AloisiAlk_maxs(:,2),'r')
xlim([0 550])
set(gca, 'xdir', 'reverse')
box on
ylabel('Alk (mequiv)')
ylim([0 10])
xlabel('Age (Ma)')

t_data1_ax8 = nexttile;

Alk_50 = prctile(Alk',50);
Alk_10 = prctile(Alk',10);
Alk_90 = prctile(Alk',90);
neg_Alk = Alk_50 - Alk_10;
pos_Alk = Alk_90 - Alk_50;

Alk_50 = Alk_50';
neg_Alk = neg_Alk';
pos_Alk = pos_Alk';

errorbar(ages(mineral == 'aragonite' & depenv == 'shoal'),...
    Alk_50(mineral == 'aragonite' & depenv == 'shoal'),...
   neg_Alk(mineral == 'aragonite' & depenv == 'shoal'),...
   pos_Alk(mineral == 'aragonite' & depenv == 'shoal'),'o',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
hold on
errorbar(ages(mineral == 'aragonite' & depenv == 'tidal'),...
    Alk_50(mineral == 'aragonite' & depenv == 'tidal'),...
   neg_Alk(mineral == 'aragonite' & depenv == 'tidal'),...
   pos_Alk(mineral == 'aragonite' & depenv == 'tidal'),'d',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'high_energy'),...
    Alk_50(mineral == 'aragonite' & depenv == 'high_energy'),...
   neg_Alk(mineral == 'aragonite' & depenv == 'high_energy'),...
   pos_Alk(mineral == 'aragonite' & depenv == 'high_energy'),'s',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'low_energy'),...
    Alk_50(mineral == 'aragonite' & depenv == 'low_energy'),...
   neg_Alk(mineral == 'aragonite' & depenv == 'low_energy'),...
   pos_Alk(mineral == 'aragonite' & depenv == 'low_energy'),'v',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'other'),...
    Alk_50(mineral == 'aragonite' & depenv == 'other'),...
   neg_Alk(mineral == 'aragonite' & depenv == 'other'),...
   pos_Alk(mineral == 'aragonite' & depenv == 'other'),'p',...
   'Color',colors(1,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'calcite' & depenv == 'shoal'),...
    Alk_50(mineral == 'calcite' & depenv == 'shoal'),...
   neg_Alk(mineral == 'calcite' & depenv == 'shoal'),...
   pos_Alk(mineral == 'calcite' & depenv == 'shoal'),'o',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'tidal'),...
    Alk_50(mineral == 'calcite' & depenv == 'tidal'),...
   neg_Alk(mineral == 'calcite' & depenv == 'tidal'),...
   pos_Alk(mineral == 'calcite' & depenv == 'tidal'),'d',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'high_energy'),...
    Alk_50(mineral == 'calcite' & depenv == 'high_energy'),...
   neg_Alk(mineral == 'calcite' & depenv == 'high_energy'),...
   pos_Alk(mineral == 'calcite' & depenv == 'high_energy'),'s',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'low_energy'),...
    Alk_50(mineral == 'calcite' & depenv == 'low_energy'),...
   neg_Alk(mineral == 'calcite' & depenv == 'low_energy'),...
   pos_Alk(mineral == 'calcite' & depenv == 'low_energy'),'v',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'other'),...
    Alk_50(mineral == 'calcite' & depenv == 'other'),...
   neg_Alk(mineral == 'calcite' & depenv == 'other'),...
   pos_Alk(mineral == 'calcite' & depenv == 'other'),'p',...
   'Color',colors(2,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'shoal'),...
    Alk_50(mineral == 'bimineralic' & depenv == 'shoal'),...
   neg_Alk(mineral == 'bimineralic' & depenv == 'shoal'),...
   pos_Alk(mineral == 'bimineralic' & depenv == 'shoal'),'o',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'tidal'),...
    Alk_50(mineral == 'bimineralic' & depenv == 'tidal'),...
   neg_Alk(mineral == 'bimineralic' & depenv == 'tidal'),...
   pos_Alk(mineral == 'bimineralic' & depenv == 'tidal'),'d',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'high_energy'),...
    Alk_50(mineral == 'bimineralic' & depenv == 'high_energy'),...
   neg_Alk(mineral == 'bimineralic' & depenv == 'high_energy'),...
   pos_Alk(mineral == 'bimineralic' & depenv == 'high_energy'),'s',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'low_energy'),...
    Alk_50(mineral == 'bimineralic' & depenv == 'low_energy'),...
   neg_Alk(mineral == 'bimineralic' & depenv == 'low_energy'),...
   pos_Alk(mineral == 'bimineralic' & depenv == 'low_energy'),'v',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'other'),...
    Alk_50(mineral == 'bimineralic' & depenv == 'other'),...
   neg_Alk(mineral == 'bimineralic' & depenv == 'other'),...
   pos_Alk(mineral == 'bimineralic' & depenv == 'other'),'p',...
   'Color',colors(3,:),'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))

Alk_50_sort = Alk_50(sortorder);
loessfit_Alk = smooth(agesort,Alk_50_sort,0.1,'rlowess');

%f = @(xy) smooth(xy(:,1),xy(:,2),0.1,'rlowess');
yboot2_Alk = bootstrp(1000,f,[agesort,Alk_50_sort]);
stdloess_Alk = std(yboot2_Alk);

plot(agesort,loessfit_Alk,'k')
plot(agesort,loessfit_Alk+stdloess_Alk','r')
plot(agesort,loessfit_Alk-stdloess_Alk','r')

box on
xlim([0 550])
set(gca, 'xdir', 'reverse')
ylim([0 10])
xlabel('Age (Ma)')



linkaxes([t_data1_ax1,t_data1_ax3,t_data1_ax5,t_data1_ax7],'x')
xticklabels(t_data1_ax1,{})
xticklabels(t_data1_ax3,{})
xticklabels(t_data1_ax5,{})
linkaxes([t_data1_ax2,t_data1_ax4,t_data1_ax6,t_data1_ax8],'x')
xticklabels(t_data1_ax2,{})
xticklabels(t_data1_ax4,{})
xticklabels(t_data1_ax6,{})
linkaxes([t_data1_ax1,t_data1_ax2],'y')
yticklabels(t_data1_ax2,{})
linkaxes([t_data1_ax3,t_data1_ax4],'y')
yticklabels(t_data1_ax4,{})
linkaxes([t_data1_ax5,t_data1_ax6],'y')
yticklabels(t_data1_ax6,{})
linkaxes([t_data1_ax7,t_data1_ax8],'y')
yticklabels(t_data1_ax8,{})
t_data1.TileSpacing = 'tight';

%%
%This will generate a panel of figures as shown in Figure 3 of the main
%text.

Figure3 = figure;

colors = magma(4);

t_data2 = tiledlayout(5,1);

t_data2_ax1 = nexttile;
errorbar(ages(mineral == 'aragonite' & depenv == 'shoal'),...
    Omega_ca_50(mineral == 'aragonite' & depenv == 'shoal'),...
   neg(mineral == 'aragonite' & depenv == 'shoal'),...
   pos(mineral == 'aragonite' & depenv == 'shoal'),'o',...
   'Color',colors(1,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
hold on
errorbar(ages(mineral == 'aragonite' & depenv == 'tidal'),...
    Omega_ca_50(mineral == 'aragonite' & depenv == 'tidal'),...
   neg(mineral == 'aragonite' & depenv == 'tidal'),...
   pos(mineral == 'aragonite' & depenv == 'tidal'),'d',...
   'Color',colors(1,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'high_energy'),...
    Omega_ca_50(mineral == 'aragonite' & depenv == 'high_energy'),...
   neg(mineral == 'aragonite' & depenv == 'high_energy'),...
   pos(mineral == 'aragonite' & depenv == 'high_energy'),'s',...
   'Color',colors(1,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'low_energy'),...
    Omega_ca_50(mineral == 'aragonite' & depenv == 'low_energy'),...
   neg(mineral == 'aragonite' & depenv == 'low_energy'),...
   pos(mineral == 'aragonite' & depenv == 'low_energy'),'v',...
   'Color',colors(1,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'aragonite' & depenv == 'other'),...
    Omega_ca_50(mineral == 'aragonite' & depenv == 'other'),...
   neg(mineral == 'aragonite' & depenv == 'other'),...
   pos(mineral == 'aragonite' & depenv == 'other'),'p',...
   'Color',colors(1,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(ages(mineral == 'calcite' & depenv == 'shoal'),...
    Omega_ca_50(mineral == 'calcite' & depenv == 'shoal'),...
   neg(mineral == 'calcite' & depenv == 'shoal'),...
   pos(mineral == 'calcite' & depenv == 'shoal'),'o',...
   'Color',colors(2,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'tidal'),...
    Omega_ca_50(mineral == 'calcite' & depenv == 'tidal'),...
   neg(mineral == 'calcite' & depenv == 'tidal'),...
   pos(mineral == 'calcite' & depenv == 'tidal'),'d',...
   'Color',colors(2,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'high_energy'),...
    Omega_ca_50(mineral == 'calcite' & depenv == 'high_energy'),...
   neg(mineral == 'calcite' & depenv == 'high_energy'),...
   pos(mineral == 'calcite' & depenv == 'high_energy'),'s',...
   'Color',colors(2,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'low_energy'),...
    Omega_ca_50(mineral == 'calcite' & depenv == 'low_energy'),...
   neg(mineral == 'calcite' & depenv == 'low_energy'),...
   pos(mineral == 'calcite' & depenv == 'low_energy'),'v',...
   'Color',colors(2,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'calcite' & depenv == 'other'),...
    Omega_ca_50(mineral == 'calcite' & depenv == 'other'),...
   neg(mineral == 'calcite' & depenv == 'other'),...
   pos(mineral == 'calcite' & depenv == 'other'),'p',...
   'Color',colors(2,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'shoal'),...
    Omega_ca_50(mineral == 'bimineralic' & depenv == 'shoal'),...
   neg(mineral == 'bimineralic' & depenv == 'shoal'),...
   pos(mineral == 'bimineralic' & depenv == 'shoal'),'o',...
   'Color',colors(3,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'tidal'),...
    Omega_ca_50(mineral == 'bimineralic' & depenv == 'tidal'),...
   neg(mineral == 'bimineralic' & depenv == 'tidal'),...
   pos(mineral == 'bimineralic' & depenv == 'tidal'),'d',...
   'Color',colors(3,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'high_energy'),...
    Omega_ca_50(mineral == 'bimineralic' & depenv == 'high_energy'),...
   neg(mineral == 'bimineralic' & depenv == 'high_energy'),...
   pos(mineral == 'bimineralic' & depenv == 'high_energy'),'s',...
   'Color',colors(3,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'low_energy'),...
    Omega_ca_50(mineral == 'bimineralic' & depenv == 'low_energy'),...
   neg(mineral == 'bimineralic' & depenv == 'low_energy'),...
   pos(mineral == 'bimineralic' & depenv == 'low_energy'),'v',...
   'Color',colors(3,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(ages(mineral == 'bimineralic' & depenv == 'other'),...
    Omega_ca_50(mineral == 'bimineralic' & depenv == 'other'),...
   neg(mineral == 'bimineralic' & depenv == 'other'),...
   pos(mineral == 'bimineralic' & depenv == 'other'),'p',...
   'Color',colors(3,:),'MarkerSize',5,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
xline(160,'g');
xline(165,'g');
xline(251,'g');
xline(489,'g');
xline(443,'g');
xline(465,'g');
xline(420,'g'); %Lau event
xline(183.1,'g'); %Toarcian OAE
xline(200,'g'); %T-J extinction
xline(120,'g'); %OAE 1a
xline(93,'g'); %OAE 2

xlim([0 550])
set(gca, 'xdir', 'reverse')
box on
ylabel('\Omega_C_a')
ylim([0 30])
title('seawater \Omega reconstructed via ooid size')

t_data2_ax2 = nexttile;
microbereefs = readmatrix('Kiessling_2009_data_clean.xlsx','Range',...
    'B2:E56');
edges2 = flip([microbereefs(:,2);0])';
counts2 = flip(microbereefs(:,4))';
histogram('BinEdges',edges2,'BinCounts',counts2)
xlim([0 550])
set(gca, 'xdir', 'reverse')
ylabel('number of microbial reefs')
title('microbial reef abundance (Kiessling 2009)')

t_data2_ax3 = nexttile;
calc_cyano = readmatrix('Arp_SupplTab2.xls','Range','E5:F532');
counts3 = calc_cyano(:,1);
counts3(isnan(counts3)) = [];
edges3 = calc_cyano(:,2);
edges3(isnan(edges3)) = [];
edges3 = [0;edges3];
histogram('BinEdges',edges3','BinCounts',counts3')
xlim([0 550])
set(gca, 'xdir', 'reverse')

ylabel('calcified cyanobacteria occurrences')
title('calcified cyanobacteria (Arp et al. 2001)')

t_data2_ax4 = nexttile;
hardgrounds = readmatrix('Hardgrounds_WrightCherns2016.xlsx','Range',...
    'B2:C12');
edges4 = flip([hardgrounds(:,2);0])';
counts4 = flip(hardgrounds(:,1))';
histogram('BinEdges',edges4,'BinCounts',counts4)
xlim([0 550])
xticks([0:50:550])
set(gca, 'xdir', 'reverse')
ylabel('hardgrounds (# of pubs)')
title('hardground abundance (Wright & Cherns 2016)')

t_data2_ax5 = nexttile;

Smith_etal_data = readmatrix('Smith_etal_2021_histogramdata.xlsx','Sheet',...
    'histogram_counts','Range','B2:H14');
edges5 = [Smith_etal_data(:,1);0];
tepeecounts = Smith_etal_data(:,6);
pisoidcounts = Smith_etal_data(:,7);

histogram('BinEdges',flip(edges5)','BinCounts',flip(tepeecounts)');
hold on
histogram('BinEdges',flip(edges5)','BinCounts',flip(pisoidcounts)')
box on
xlim([0 550])
set(gca, 'xdir', 'reverse')
ylabel('abundance of tepees or pisoids')
title('arid coastal carbonates (Smith et al. 2021)')

linkaxes([t_data2_ax1,t_data2_ax2,t_data2_ax3,t_data2_ax4,...
    t_data2_ax5],'x')
xlabel(t_data2,'age (Ma)')
xticklabels(t_data2_ax1,{})
xticklabels(t_data2_ax2,{})
xticklabels(t_data2_ax3,{})
xticklabels(t_data2_ax4,{})
t_data2.TileSpacing = 'tight';
