%%
%PhanOomega: reconstructing the carbonate chemistry of Phanerozoic seawater
%using ooid size data

%This code will regenerate some of the figures in the supplement.
%Supplementary figures S1 & S3 can be generated using main figure code (for
%different model configurations). Supplementary figure S4 shows data from
%Li et al. (2021).

%This code was written by Lizzy Trower in Matlab R2021b. This version was
%last edited in May 2022.

%%
%Supplementary Figure S2
clear

%load relevant model run .mat file
load("MCv2data_01242022.mat")
load('AKdata_formation.mat','paleolat')

Omega_ca_50 = prctile(Omega_ca',50);

%load Scotese et al 2021 tropical temperature data
troptemps = readmatrix('Part 4. Phanerozoic_Paleotemperature_Summaryv4.xlsx',...
    'Sheet','TropvsGAT 1my','Range','A2:C542');
troptemps(:,2) = [];
troptemps_rescale = interp1(troptemps(:,1),troptemps(:,2),ages);

%Load Demicco et al Ca and Mg data
[concCa_D] = readmatrix('Demicco_panelD_data.xlsx','Sheet','Ca',...
    'Range','A2:B45');
[concMg_D] = readmatrix('Demicco_panelD_data.xlsx','Sheet','Mg',...
    'Range','A2:B44');

%Load other ion data from Demicco et al 2005
[concSO4] = readmatrix('Demicco_panelD_data.xlsx','Sheet','SO4',...
    'Range','A2:B43');
[concNa] = readmatrix('Demicco_panelD_data.xlsx','Sheet','Na',...
    'Range','A2:B45');
[concK] = readmatrix('Demicco_panelD_data.xlsx','Sheet','K',...
    'Range','A2:B45');

%Load pCO2 data from Foster et al. 2017
pCO2_420to0 = readmatrix('41467_2017_BFncomms14845_MOESM2875_ESM.xlsx',...
    'Range','A3:E842');
pCO2_420to0_sigma = pCO2_420to0(:,5) - pCO2_420to0(:,2);

%Load model pCO2 from Berner 2006
pCO2_540to420 = readmatrix('GEOCARBSULF.xlsx','Range','A2:C19');
pCO2_540to420(:,2) = [];
pCO2_540to420(15:end,:) = [];

%combine
pCO2_stack = cat(1,pCO2_420to0(:,1:2),pCO2_540to420);
pCO2_rescale = interp1(pCO2_stack(:,1),pCO2_stack(:,2),ages);

%rescale datasets so they're in the same age bins as the ooid size data
concCa_rescale = interp1(concCa_D(:,1),concCa_D(:,2),ages);
concCa_rescale(end-7:end) = 10.3;

concMg_rescale = interp1(concMg_D(:,1),concMg_D(:,2),ages);
concMg_rescale(end-7:end) = 53;

concNa_rescale = interp1(concNa(:,1),concNa(:,2),ages);
concNa_rescale(end-7:end) = 469;

concK_rescale = interp1(concK(:,1),concK(:,2),ages);
concK_rescale(end-7:end) = 10.2;

concSO4_rescale = interp1(concSO4(:,1),concSO4(:,2),ages);
concSO4_rescale(end-9:end) = 28;

%Load and rescale [Cl] data from Hay et al. 2006
concCl = readmatrix('Hay_etal_chloride.xlsx','Range','A2:E32');
concCl_rescale = interp1(concCl(:,1),concCl(:,5),ages);
concCl_rescale(1:4) = concCl_rescale(5);

HCO3 = zeros(length(ages),1);
CO3 = zeros(length(ages),1);

parfor count = 1:length(ages)
    temp = troptemps_rescale(count); 
    [Alk,DIC,pH,Omega_ar,HCO3(count),CO3(count)] = ...
        phreeqc_oomega_calcite_spec(temp,...
        concCa_rescale(count),concMg_rescale(count),...
        concK_rescale(count),concSO4_rescale(count),...
        concNa_rescale(count),concCl_rescale(count),...
        pCO2_rescale(count),Omega_ca_50(count));
end

%Data curation step
Stokes_95 = prctile(Stokes,95,2);
Stokes_thresh = find(Stokes_95>=9);

Omega_ca = Omega_ca_50(Stokes_thresh);
ages = ages(Stokes_thresh);
HCO3 = HCO3(Stokes_thresh);
CO3 = CO3(Stokes_thresh);

suppfig_S2 = figure;

tiledlayout(5,1);

suppfig_S2_ax1 = nexttile;

scatter(ages,(HCO3)*10^3,'.')
xlim([0 550])
set(gca, 'xdir', 'reverse')
box on
ylabel('[HCO_3^-] (mmol/kgw)')

suppfig_S2_ax2 = nexttile;

scatter(ages,(CO3)*10^6,'.')
xlim([0 550])
set(gca, 'xdir', 'reverse')
ylabel('[CO_3^2^-] (\mumol/kgw)')
box on
ylim([0 100])

suppfig_S2_ax3 = nexttile;

scatter((HCO3)*10^3,(Omega_ca),'.')
xlabel('[HCO_3^-] (mmol/kgw)')
ylabel('log(\Omega_C_a)')
box on

suppfig_S2_ax4 = nexttile;

scatter((CO3)*10^6,Omega_ca,'.')
xlabel('[CO_3^2^-] (\mumol/kgw)')
ylabel('log(\Omega_C_a)')
box on
xlim([0 100])

suppfig_S2_ax5 = nexttile;

Ca = concCa_rescale(Stokes_thresh);

scatter(Ca,Omega_ca,'.')
xlabel('[Ca] (mmol/kgw)')
ylabel('\Omega_C_a')
box on

%%
%Supplementary Figure S5

%load relevant model run .mat file
load("MCv2data_01242022.mat")
load('AKdata_formation.mat','paleolat')

%Data curation step to take out datapoints for which
%the mean particular Stokes number is below the threshold, since those
%grains do not have sufficient kinetic energy relative to fluid viscosity
%to abrade and therefore the equilibrium ooid size model cannot be applied.

%This uses the 95th percentile Stokes # - still includes grains for which
%>5% of simulations are large enough to abrade (so pretty conservative in
%excluding data).

Stokes_95 = prctile(Stokes,95,2);
Stokes_thresh = find(Stokes_95>=9);

Omega_ca = Omega_ca(Stokes_thresh,:);
ages = ages(Stokes_thresh);
mineral = mineral(Stokes_thresh);
DIC = DIC(Stokes_thresh,:);
Alk = Alk(Stokes_thresh,:);
pH = pH(Stokes_thresh,:);
depenv = depenv(Stokes_thresh);
paleolat = paleolat(Stokes_thresh);

Omega_ca_50 = prctile(Omega_ca',50);
Omega_ca_10 = prctile(Omega_ca',10);
Omega_ca_90 = prctile(Omega_ca',90);
neg = Omega_ca_50 - Omega_ca_10;
pos = Omega_ca_90 - Omega_ca_50;

suppfig_S5 = figure;
tiledlayout(4,2);

abs_paleolat = abs(paleolat);

colors = magma(4);

suppfig_S5_t1 = nexttile;

errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'shoal'),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'shoal'),...
   neg(mineral == 'aragonite' & depenv == 'shoal'),...
   pos(mineral == 'aragonite' & depenv == 'shoal'),'horizontal','o',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
hold on
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'tidal'),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'tidal'),...
    neg(mineral == 'aragonite' & depenv == 'tidal'),...
   pos(mineral == 'aragonite' & depenv == 'tidal'),'horizontal','d',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'high_energy'),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'high_energy'),...
    neg(mineral == 'aragonite' & depenv == 'high_energy'),...
   pos(mineral == 'aragonite' & depenv == 'high_energy'),'horizontal','s',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'low_energy'),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'low_energy'),...
    neg(mineral == 'aragonite' & depenv == 'low_energy'),...
   pos(mineral == 'aragonite' & depenv == 'low_energy'),'horizontal','v',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'other'),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'other'),...
    neg(mineral == 'aragonite' & depenv == 'other'),...
   pos(mineral == 'aragonite' & depenv == 'other'),'horizontal','p',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'shoal'),...
   abs_paleolat(mineral == 'calcite' & depenv == 'shoal'),...
    neg(mineral == 'calcite' & depenv == 'shoal'),...
   pos(mineral == 'calcite' & depenv == 'shoal'),'horizontal','o',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'tidal'),...
   abs_paleolat(mineral == 'calcite' & depenv == 'tidal'),...
    neg(mineral == 'calcite' & depenv == 'tidal'),...
   pos(mineral == 'calcite' & depenv == 'tidal'),'horizontal','d',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'high_energy'),...
   abs_paleolat(mineral == 'calcite' & depenv == 'high_energy'),...
    neg(mineral == 'calcite' & depenv == 'high_energy'),...
   pos(mineral == 'calcite' & depenv == 'high_energy'),'horizontal','s',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'low_energy'),...
   abs_paleolat(mineral == 'calcite' & depenv == 'low_energy'),...
    neg(mineral == 'calcite' & depenv == 'low_energy'),...
   pos(mineral == 'calcite' & depenv == 'low_energy'),'horizontal','v',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'other'),...
   abs_paleolat(mineral == 'calcite' & depenv == 'other'),...
    neg(mineral == 'calcite' & depenv == 'other'),...
   pos(mineral == 'calcite' & depenv == 'other'),'horizontal','p',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'shoal'),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'shoal'),...
    neg(mineral == 'bimineralic' & depenv == 'shoal'),...
   pos(mineral == 'bimineralic' & depenv == 'shoal'),'horizontal','o',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'tidal'),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'tidal'),...
    neg(mineral == 'bimineralic' & depenv == 'tidal'),...
   pos(mineral == 'bimineralic' & depenv == 'tidal'),'horizontal','d',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'high_energy'),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'high_energy'),...
    neg(mineral == 'bimineralic' & depenv == 'high_energy'),...
   pos(mineral == 'bimineralic' & depenv == 'high_energy'),'horizontal','s',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'low_energy'),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'low_energy'),...
    neg(mineral == 'bimineralic' & depenv == 'low_energy'),...
   pos(mineral == 'bimineralic' & depenv == 'low_energy'),'horizontal','v',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'other'),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'other'),...
    neg(mineral == 'bimineralic' & depenv == 'other'),...
   pos(mineral == 'bimineralic' & depenv == 'other'),'horizontal','p',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))

rectangle('Position',[4.68 0 (6.06-4.68) 10])
rectangle('Position',[4.23 10 (6.18-4.23) 20])
rectangle('Position',[2.82 30 (5.87-2.82) 20])

X = [ones(size(ages(Omega_ca_50 <25))) ages(Omega_ca_50 <25)...
    abs_paleolat(Omega_ca_50 <25) ages(Omega_ca_50 <25).*abs_paleolat(Omega_ca_50 <25)];
[b,~,r,rint,stats] = regress(Omega_ca_50(Omega_ca_50 <25)',X);
x1fit = 0:50:550;
x2fit = 0:5:50;
[X1FIT,X2FIT] = meshgrid(x1fit,x2fit);
YFIT = b(1) + b(2)*X1FIT + b(3)*X2FIT + b(4)*X1FIT.*X2FIT;

contour(YFIT,X2FIT,X1FIT,0:100:500)
c1 = colorbar;
c1.Label.String = 'age(Ma)';
caxis([0 550])

box on
ylim([0 50])
xlabel('\Omega_C_a')
xlim([0 30])

suppfig_S5_t2 = nexttile;

scatter(ages(mineral == 'aragonite' & depenv == 'shoal'),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'shoal'),...
   50,colors(1,:),'filled','o')
hold on
scatter(ages(mineral == 'aragonite' & depenv == 'tidal'),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'tidal'),...
   50,colors(1,:),'filled','d')
scatter(ages(mineral == 'aragonite' & depenv == 'high_energy'),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'high_energy'),...
   50,colors(1,:),'filled','s')
scatter(ages(mineral == 'aragonite' & depenv == 'low_energy'),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'low_energy'),...
    50,colors(1,:),'filled','v')
scatter(ages(mineral == 'aragonite' & depenv == 'other'),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'other'),...
   50,colors(1,:),'filled','p')
scatter(ages(mineral == 'calcite' & depenv == 'shoal'),...
   abs_paleolat(mineral == 'calcite' & depenv == 'shoal'),...
   50,colors(2,:),'filled','o')
scatter(ages(mineral == 'calcite' & depenv == 'tidal'),...
   abs_paleolat(mineral == 'calcite' & depenv == 'tidal'),...
    50,colors(2,:),'filled','d')
scatter(ages(mineral == 'calcite' & depenv == 'high_energy'),...
   abs_paleolat(mineral == 'calcite' & depenv == 'high_energy'),...
    50,colors(2,:),'filled','s')
scatter(ages(mineral == 'calcite' & depenv == 'low_energy'),...
   abs_paleolat(mineral == 'calcite' & depenv == 'low_energy'),...
     50,colors(2,:),'filled','v')
scatter(ages(mineral == 'calcite' & depenv == 'other'),...
   abs_paleolat(mineral == 'calcite' & depenv == 'other'),...
   50,colors(2,:),'filled','p')
scatter(ages(mineral == 'bimineralic' & depenv == 'shoal'),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'shoal'),...
   50,colors(3,:),'filled','o')
scatter(ages(mineral == 'bimineralic' & depenv == 'tidal'),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'tidal'),...
    50,colors(3,:),'filled','d')
scatter(ages(mineral == 'bimineralic' & depenv == 'high_energy'),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'high_energy'),...
    50,colors(3,:),'filled','s')
scatter(ages(mineral == 'bimineralic' & depenv == 'low_energy'),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'low_energy'),...
     50,colors(3,:),'filled','v')
scatter(ages(mineral == 'bimineralic' & depenv == 'other'),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'other'),...
   50,colors(3,:),'filled','p')

% contour(X1FIT,X2FIT,YFIT)
% c2 = colorbar;
% c2.Label.String = '\Omega_C_a';

box on
ylim([0 50])
xlim([0 550])
set(gca, 'xdir', 'reverse')

suppfig_S5_t3 = nexttile;

errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'shoal' & ages < 150),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'shoal' & ages < 150),...
   neg(mineral == 'aragonite' & depenv == 'shoal' & ages < 150),...
   pos(mineral == 'aragonite' & depenv == 'shoal' & ages < 150),'horizontal','o',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
hold on
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'tidal' & ages < 150),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'tidal' & ages < 150),...
    neg(mineral == 'aragonite' & depenv == 'tidal' & ages < 150),...
   pos(mineral == 'aragonite' & depenv == 'tidal' & ages < 150),'horizontal','d',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'high_energy' & ages < 150),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'high_energy' & ages < 150),...
    neg(mineral == 'aragonite' & depenv == 'high_energy' & ages < 150),...
   pos(mineral == 'aragonite' & depenv == 'high_energy' & ages < 150),'horizontal','s',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'low_energy' & ages < 150),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'low_energy' & ages < 150),...
    neg(mineral == 'aragonite' & depenv == 'low_energy' & ages < 150),...
   pos(mineral == 'aragonite' & depenv == 'low_energy' & ages < 150),'horizontal','v',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'other' & ages < 150),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'other' & ages < 150),...
    neg(mineral == 'aragonite' & depenv == 'other' & ages < 150),...
   pos(mineral == 'aragonite' & depenv == 'other' & ages < 150),'horizontal','p',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'shoal' & ages < 150),...
   abs_paleolat(mineral == 'calcite' & depenv == 'shoal' & ages < 150),...
    neg(mineral == 'calcite' & depenv == 'shoal' & ages < 150),...
   pos(mineral == 'calcite' & depenv == 'shoal' & ages < 150),'horizontal','o',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'tidal' & ages < 150),...
   abs_paleolat(mineral == 'calcite' & depenv == 'tidal' & ages < 150),...
    neg(mineral == 'calcite' & depenv == 'tidal' & ages < 150),...
   pos(mineral == 'calcite' & depenv == 'tidal' & ages < 150),'horizontal','d',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'high_energy' & ages < 150),...
   abs_paleolat(mineral == 'calcite' & depenv == 'high_energy' & ages < 150),...
    neg(mineral == 'calcite' & depenv == 'high_energy' & ages < 150),...
   pos(mineral == 'calcite' & depenv == 'high_energy' & ages < 150),'horizontal','s',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'low_energy' & ages < 150),...
   abs_paleolat(mineral == 'calcite' & depenv == 'low_energy' & ages < 150),...
    neg(mineral == 'calcite' & depenv == 'low_energy' & ages < 150),...
   pos(mineral == 'calcite' & depenv == 'low_energy' & ages < 150),'horizontal','v',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'other' & ages < 150),...
   abs_paleolat(mineral == 'calcite' & depenv == 'other' & ages < 150),...
    neg(mineral == 'calcite' & depenv == 'other' & ages < 150),...
   pos(mineral == 'calcite' & depenv == 'other' & ages < 150),'horizontal','p',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'shoal' & ages < 150),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'shoal' & ages < 150),...
    neg(mineral == 'bimineralic' & depenv == 'shoal' & ages < 150),...
   pos(mineral == 'bimineralic' & depenv == 'shoal' & ages < 150),'horizontal','o',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'tidal' & ages < 150),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'tidal' & ages < 150),...
    neg(mineral == 'bimineralic' & depenv == 'tidal' & ages < 150),...
   pos(mineral == 'bimineralic' & depenv == 'tidal' & ages < 150),'horizontal','d',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'high_energy' & ages < 150),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'high_energy' & ages < 150),...
    neg(mineral == 'bimineralic' & depenv == 'high_energy' & ages < 150),...
   pos(mineral == 'bimineralic' & depenv == 'high_energy' & ages < 150),'horizontal','s',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'low_energy' & ages < 150),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'low_energy' & ages < 150),...
    neg(mineral == 'bimineralic' & depenv == 'low_energy' & ages < 150),...
   pos(mineral == 'bimineralic' & depenv == 'low_energy' & ages < 150),'horizontal','v',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'other' & ages < 150),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'other' & ages < 150),...
    neg(mineral == 'bimineralic' & depenv == 'other' & ages < 150),...
   pos(mineral == 'bimineralic' & depenv == 'other' & ages < 150),'horizontal','p',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))

box on
ylim([0 50])
xlabel('\Omega_C_a')
xlim([0 30])

suppfig_S5_t4 = nexttile;

scatter(ages(mineral == 'aragonite' & depenv == 'shoal' & ages < 150),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'shoal' & ages < 150),...
   50,colors(1,:),'filled','o')
hold on
scatter(ages(mineral == 'aragonite' & depenv == 'tidal' & ages < 150),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'tidal' & ages < 150),...
   50,colors(1,:),'filled','d')
scatter(ages(mineral == 'aragonite' & depenv == 'high_energy' & ages < 150),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'high_energy' & ages < 150),...
   50,colors(1,:),'filled','s')
scatter(ages(mineral == 'aragonite' & depenv == 'low_energy' & ages < 150),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'low_energy' & ages < 150),...
    50,colors(1,:),'filled','v')
scatter(ages(mineral == 'aragonite' & depenv == 'other' & ages < 150),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'other' & ages < 150),...
   50,colors(1,:),'filled','p')
scatter(ages(mineral == 'calcite' & depenv == 'shoal' & ages < 150),...
   abs_paleolat(mineral == 'calcite' & depenv == 'shoal' & ages < 150),...
   50,colors(2,:),'filled','o')
scatter(ages(mineral == 'calcite' & depenv == 'tidal' & ages < 150),...
   abs_paleolat(mineral == 'calcite' & depenv == 'tidal' & ages < 150),...
    50,colors(2,:),'filled','d')
scatter(ages(mineral == 'calcite' & depenv == 'high_energy' & ages < 150),...
   abs_paleolat(mineral == 'calcite' & depenv == 'high_energy' & ages < 150),...
    50,colors(2,:),'filled','s')
scatter(ages(mineral == 'calcite' & depenv == 'low_energy' & ages < 150),...
   abs_paleolat(mineral == 'calcite' & depenv == 'low_energy' & ages < 150),...
     50,colors(2,:),'filled','v')
scatter(ages(mineral == 'calcite' & depenv == 'other' & ages < 150),...
   abs_paleolat(mineral == 'calcite' & depenv == 'other' & ages < 150),...
   50,colors(2,:),'filled','p')
scatter(ages(mineral == 'bimineralic' & depenv == 'shoal' & ages < 150),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'shoal' & ages < 150),...
   50,colors(3,:),'filled','o')
scatter(ages(mineral == 'bimineralic' & depenv == 'tidal' & ages < 150),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'tidal' & ages < 150),...
    50,colors(3,:),'filled','d')
scatter(ages(mineral == 'bimineralic' & depenv == 'high_energy' & ages < 150),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'high_energy' & ages < 150),...
    50,colors(3,:),'filled','s')
scatter(ages(mineral == 'bimineralic' & depenv == 'low_energy' & ages < 150),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'low_energy' & ages < 150),...
     50,colors(3,:),'filled','v')
scatter(ages(mineral == 'bimineralic' & depenv == 'other' & ages < 150),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'other' & ages < 150),...
   50,colors(3,:),'filled','p')

box on
ylim([0 50])
xlim([0 150])
set(gca, 'xdir', 'reverse')

suppfig_S5_t5 = nexttile;

errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   neg(mineral == 'aragonite' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   pos(mineral == 'aragonite' & depenv == 'shoal' & ages > 200 & ages <= 300),'horizontal','o',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
hold on
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'tidal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'tidal' & ages > 200 & ages <= 300),...
    neg(mineral == 'aragonite' & depenv == 'tidal' & ages > 200 & ages <= 300),...
   pos(mineral == 'aragonite' & depenv == 'tidal' & ages > 200 & ages <= 300),'horizontal','d',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
    neg(mineral == 'aragonite' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
   pos(mineral == 'aragonite' & depenv == 'high_energy' & ages > 200 & ages <= 300),'horizontal','s',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
    neg(mineral == 'aragonite' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
   pos(mineral == 'aragonite' & depenv == 'low_energy' & ages > 200 & ages <= 300),'horizontal','v',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'other' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'other' & ages > 200 & ages <= 300),...
    neg(mineral == 'aragonite' & depenv == 'other' & ages > 200 & ages <= 300),...
   pos(mineral == 'aragonite' & depenv == 'other' & ages > 200 & ages <= 300),'horizontal','p',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'calcite' & depenv == 'shoal' & ages > 200 & ages <= 300),...
    neg(mineral == 'calcite' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   pos(mineral == 'calcite' & depenv == 'shoal' & ages > 200 & ages <= 300),'horizontal','o',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'tidal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'calcite' & depenv == 'tidal' & ages > 200 & ages <= 300),...
    neg(mineral == 'calcite' & depenv == 'tidal' & ages > 200 & ages <= 300),...
   pos(mineral == 'calcite' & depenv == 'tidal' & ages > 200 & ages <= 300),'horizontal','d',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'calcite' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
    neg(mineral == 'calcite' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
   pos(mineral == 'calcite' & depenv == 'high_energy' & ages > 200 & ages <= 300),'horizontal','s',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'calcite' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
    neg(mineral == 'calcite' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
   pos(mineral == 'calcite' & depenv == 'low_energy' & ages > 200 & ages <= 300),'horizontal','v',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'other' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'calcite' & depenv == 'other' & ages > 200 & ages <= 300),...
    neg(mineral == 'calcite' & depenv == 'other' & ages > 200 & ages <= 300),...
   pos(mineral == 'calcite' & depenv == 'other' & ages > 200 & ages <= 300),'horizontal','p',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'shoal' & ages > 200 & ages <= 300),...
    neg(mineral == 'bimineralic' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   pos(mineral == 'bimineralic' & depenv == 'shoal' & ages > 200 & ages <= 300),'horizontal','o',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'tidal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'tidal' & ages > 200 & ages <= 300),...
    neg(mineral == 'bimineralic' & depenv == 'tidal' & ages > 200 & ages <= 300),...
   pos(mineral == 'bimineralic' & depenv == 'tidal' & ages > 200 & ages <= 300),'horizontal','d',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
    neg(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
   pos(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 200 & ages <= 300),'horizontal','s',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
    neg(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
   pos(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 200 & ages <= 300),'horizontal','v',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'other' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'other' & ages > 200 & ages <= 300),...
    neg(mineral == 'bimineralic' & depenv == 'other' & ages > 200 & ages <= 300),...
   pos(mineral == 'bimineralic' & depenv == 'other' & ages > 200 & ages <= 300),'horizontal','p',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))

box on
ylim([0 50])
xlabel('\Omega_C_a')
xlim([0 30])

suppfig_S5_t6 = nexttile;

scatter(ages(mineral == 'aragonite' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   50,colors(1,:),'filled','o')
hold on
scatter(ages(mineral == 'aragonite' & depenv == 'tidal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'tidal' & ages > 200 & ages <= 300),...
   50,colors(1,:),'filled','d')
scatter(ages(mineral == 'aragonite' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
   50,colors(1,:),'filled','s')
scatter(ages(mineral == 'aragonite' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
    50,colors(1,:),'filled','v')
scatter(ages(mineral == 'aragonite' & depenv == 'other' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'other' & ages > 200 & ages <= 300),...
   50,colors(1,:),'filled','p')
scatter(ages(mineral == 'calcite' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'calcite' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   50,colors(2,:),'filled','o')
scatter(ages(mineral == 'calcite' & depenv == 'tidal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'calcite' & depenv == 'tidal' & ages > 200 & ages <= 300),...
    50,colors(2,:),'filled','d')
scatter(ages(mineral == 'calcite' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'calcite' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
    50,colors(2,:),'filled','s')
scatter(ages(mineral == 'calcite' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'calcite' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
     50,colors(2,:),'filled','v')
scatter(ages(mineral == 'calcite' & depenv == 'other' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'calcite' & depenv == 'other' & ages > 200 & ages <= 300),...
   50,colors(2,:),'filled','p')
scatter(ages(mineral == 'bimineralic' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'shoal' & ages > 200 & ages <= 300),...
   50,colors(3,:),'filled','o')
scatter(ages(mineral == 'bimineralic' & depenv == 'tidal' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'tidal' & ages > 200 & ages <= 300),...
    50,colors(3,:),'filled','d')
scatter(ages(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 200 & ages <= 300),...
    50,colors(3,:),'filled','s')
scatter(ages(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 200 & ages <= 300),...
     50,colors(3,:),'filled','v')
scatter(ages(mineral == 'bimineralic' & depenv == 'other' & ages > 200 & ages <= 300),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'other' & ages > 200 & ages <= 300),...
   50,colors(3,:),'filled','p')

box on
ylim([0 50])
xlim([200 300])
set(gca, 'xdir', 'reverse')


suppfig_S5_t5 = nexttile;

errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   neg(mineral == 'aragonite' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   pos(mineral == 'aragonite' & depenv == 'shoal' & ages > 400 & ages <= 500),'horizontal','o',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
hold on
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'tidal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'tidal' & ages > 400 & ages <= 500),...
    neg(mineral == 'aragonite' & depenv == 'tidal' & ages > 400 & ages <= 500),...
   pos(mineral == 'aragonite' & depenv == 'tidal' & ages > 400 & ages <= 500),'horizontal','d',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
    neg(mineral == 'aragonite' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
   pos(mineral == 'aragonite' & depenv == 'high_energy' & ages > 400 & ages <= 500),'horizontal','s',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
    neg(mineral == 'aragonite' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
   pos(mineral == 'aragonite' & depenv == 'low_energy' & ages > 400 & ages <= 500),'horizontal','v',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'aragonite' & depenv == 'other' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'other' & ages > 400 & ages <= 500),...
    neg(mineral == 'aragonite' & depenv == 'other' & ages > 400 & ages <= 500),...
   pos(mineral == 'aragonite' & depenv == 'other' & ages > 400 & ages <= 500),'horizontal','p',...
   'Color',colors(1,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(1,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'calcite' & depenv == 'shoal' & ages > 400 & ages <= 500),...
    neg(mineral == 'calcite' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   pos(mineral == 'calcite' & depenv == 'shoal' & ages > 400 & ages <= 500),'horizontal','o',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'tidal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'calcite' & depenv == 'tidal' & ages > 400 & ages <= 500),...
    neg(mineral == 'calcite' & depenv == 'tidal' & ages > 400 & ages <= 500),...
   pos(mineral == 'calcite' & depenv == 'tidal' & ages > 400 & ages <= 500),'horizontal','d',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'calcite' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
    neg(mineral == 'calcite' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
   pos(mineral == 'calcite' & depenv == 'high_energy' & ages > 400 & ages <= 500),'horizontal','s',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'calcite' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
    neg(mineral == 'calcite' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
   pos(mineral == 'calcite' & depenv == 'low_energy' & ages > 400 & ages <= 500),'horizontal','v',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'calcite' & depenv == 'other' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'calcite' & depenv == 'other' & ages > 400 & ages <= 500),...
    neg(mineral == 'calcite' & depenv == 'other' & ages > 400 & ages <= 500),...
   pos(mineral == 'calcite' & depenv == 'other' & ages > 400 & ages <= 500),'horizontal','p',...
   'Color',colors(2,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(2,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'shoal' & ages > 400 & ages <= 500),...
    neg(mineral == 'bimineralic' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   pos(mineral == 'bimineralic' & depenv == 'shoal' & ages > 400 & ages <= 500),'horizontal','o',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'tidal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'tidal' & ages > 400 & ages <= 500),...
    neg(mineral == 'bimineralic' & depenv == 'tidal' & ages > 400 & ages <= 500),...
   pos(mineral == 'bimineralic' & depenv == 'tidal' & ages > 400 & ages <= 500),'horizontal','d',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
    neg(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
   pos(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 400 & ages <= 500),'horizontal','s',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
    neg(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
   pos(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 400 & ages <= 500),'horizontal','v',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))
errorbar(Omega_ca_50(mineral == 'bimineralic' & depenv == 'other' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'other' & ages > 400 & ages <= 500),...
    neg(mineral == 'bimineralic' & depenv == 'other' & ages > 400 & ages <= 500),...
   pos(mineral == 'bimineralic' & depenv == 'other' & ages > 400 & ages <= 500),'horizontal','p',...
   'Color',colors(3,:),'MarkerSize',6,'MarkerEdgeColor','k',...
   'MarkerFaceColor',colors(3,:))

box on
ylim([0 50])
xlabel('\Omega_C_a')
xlim([0 30])

suppfig_S5_t6 = nexttile;

scatter(ages(mineral == 'aragonite' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   50,colors(1,:),'filled','o')
hold on
scatter(ages(mineral == 'aragonite' & depenv == 'tidal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'tidal' & ages > 400 & ages <= 500),...
   50,colors(1,:),'filled','d')
scatter(ages(mineral == 'aragonite' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
   50,colors(1,:),'filled','s')
scatter(ages(mineral == 'aragonite' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
    50,colors(1,:),'filled','v')
scatter(ages(mineral == 'aragonite' & depenv == 'other' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'aragonite' & depenv == 'other' & ages > 400 & ages <= 500),...
   50,colors(1,:),'filled','p')
scatter(ages(mineral == 'calcite' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'calcite' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   50,colors(2,:),'filled','o')
scatter(ages(mineral == 'calcite' & depenv == 'tidal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'calcite' & depenv == 'tidal' & ages > 400 & ages <= 500),...
    50,colors(2,:),'filled','d')
scatter(ages(mineral == 'calcite' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'calcite' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
    50,colors(2,:),'filled','s')
scatter(ages(mineral == 'calcite' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'calcite' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
     50,colors(2,:),'filled','v')
scatter(ages(mineral == 'calcite' & depenv == 'other' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'calcite' & depenv == 'other' & ages > 400 & ages <= 500),...
   50,colors(2,:),'filled','p')
scatter(ages(mineral == 'bimineralic' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'shoal' & ages > 400 & ages <= 500),...
   50,colors(3,:),'filled','o')
scatter(ages(mineral == 'bimineralic' & depenv == 'tidal' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'tidal' & ages > 400 & ages <= 500),...
    50,colors(3,:),'filled','d')
scatter(ages(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'high_energy' & ages > 400 & ages <= 500),...
    50,colors(3,:),'filled','s')
scatter(ages(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'low_energy' & ages > 400 & ages <= 500),...
     50,colors(3,:),'filled','v')
scatter(ages(mineral == 'bimineralic' & depenv == 'other' & ages > 400 & ages <= 500),...
   abs_paleolat(mineral == 'bimineralic' & depenv == 'other' & ages > 400 & ages <= 500),...
   50,colors(3,:),'filled','p')

box on
ylim([0 50])
xlim([400 500])
set(gca, 'xdir', 'reverse')

